### ISSUE TITLE
page titles and sidebar entries should not show trademark notation

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/snap-creator-framework#12]
### Page URL

https://docs.netapp.com/us-en/snap-creator-framework/index.html

### Page title

Snap Creator Framework 4.3.3

### Summary

![image](https://github.com/NetAppDocs/snap-creator-framework/assets/56453501/f1e808ba-8706-433f-b571-75f32276c264)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
The issue has been resolved https://docs.netapp.com/us-en/snap-creator-framework/index.html
