### ISSUE TITLE
the two links are on the same line

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/snap-creator-framework#13]
### Page URL

https://docs.netapp.com/us-en/snap-creator-framework/domino-ops/concept_create_a_domino_backup_using_snap_creator.html

### Page title

Backing up databases

### Summary

This is confusing. 

![image](https://github.com/NetAppDocs/snap-creator-framework/assets/56453501/24ed2d38-4fc6-4420-9e4f-a296f3a25a4c)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
The issue has been resolved https://docs.netapp.com/us-en/snap-creator-framework/domino-ops/concept_create_a_domino_backup_using_snap_creator.html
