### ISSUE TITLE
Table on this page is wrongly shifted after first column

### ISSUE THREAD

**Issue by oleimann** [NetAppDocs/snap-creator-framework#5]
Page: [Parameters to set up SnapVault](https://docs.netapp.com/us-en/snap-creator-framework/administration/reference_parameters_to_set_up_snapvault.html)

All the variables should always be in the left column, like the first entry.
Please fix.

**Comment by ntap-bmegan** [comment]
@netapp-chandaj - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @oleimann  - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-pavanrk

**Comment by netapp-ranuk** [comment]
The formatting issue has been corrected https://docs.netapp.com/us-en/snap-creator-framework/administration/reference_parameters_to_set_up_snapvault.html
