### ISSUE TITLE
additional rights for Hana user required

### ISSUE THREAD

**Issue by mschloss** [NetAppDocs/snap-creator-framework#6]
_Page:_ [Configuring the backup user and hdbuserstore](https://docs.netapp.com/us-en/snap-creator-framework/sap-hana-ops/task_configuring_the_backup_user_and_hdbuserstore.html)

in addition to BACKUP ADMIN and CATALOG READ following rights required with HANA 2.0

DATABASE BACKUP ADMIN
DATABAS RECOVER OPERATOR

could you please update the documentation accordingly? TIA Michael

**Comment by ntap-bmegan** [comment]
@netapp-chandaj - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @mschloss - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-pavanrk

**Comment by netapp-ranuk** [comment]
Hi @mschloss 
I discussed the issue internally with the Engineering team. The latest supported version is SAP HANA 2.0 SPS4 in Snap Creator Framework. The following two privileges do not exist in the Hana database studio of the specified version.:
DATABASE BACKUP ADMIN
DATABASE RECOVER OPERATOR

Please let us know if you've any further concern,
