### ISSUE TITLE
alignment missing from SC_CLONE_TARGET

### ISSUE THREAD

**Issue by jagadeeshbabuchinde** [NetAppDocs/snap-creator-framework#7]
Page: [Parameters for configuring the Snap Creator Agent host client and Snap Creator Server](https://docs.netapp.com/us-en/snap-creator-framework/administration/reference_parameters_used_to_configure_the_client_and_server.html)

**Comment by ntap-bmegan** [comment]
@netapp-chandaj - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @jagadeeshbabuchinde - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-pavanrk

**Comment by netapp-ranuk** [comment]
Hi @jagadeeshbabuchinde The table formatting has now been corrected https://docs.netapp.com/us-en/snap-creator-framework/administration/reference_parameters_used_to_configure_the_client_and_server.html.
